# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DroneSurveyingPlanning
                                 A QGIS plugin
 This plugin allows users to plan an aerial survey.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-08-21
        copyright            : (C) 2020 by Politecnico di Milano
        email                : marta1.rossi@mail.polimi.it
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DroneSurveyingPlanning class from file DroneSurveyingPlanning.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .DSP import DroneSurveyingPlanning
    return DroneSurveyingPlanning(iface)
