# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DSP_outputs.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(771, 587)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(130, 550, 331, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(190, 10, 401, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 40, 201, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(230, 40, 131, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(410, 40, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(560, 40, 131, 16))
        self.label_4.setObjectName("label_4")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 110, 631, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_2.addWidget(self.lineEdit_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_2.addWidget(self.lineEdit_6)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_2.addWidget(self.lineEdit_7)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_2.addWidget(self.lineEdit_8)
        self.layoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(50, 160, 451, 22))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_3.addWidget(self.lineEdit_9)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_3.addWidget(self.lineEdit_10)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_3.addWidget(self.lineEdit_11)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(50, 90, 141, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(220, 90, 141, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(390, 90, 151, 16))
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(550, 90, 151, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(60, 140, 151, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(230, 140, 151, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(390, 140, 171, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(140, 190, 131, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(510, 190, 131, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(50, 60, 631, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout.addWidget(self.lineEdit_3)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout.addWidget(self.lineEdit_4)
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(60, 220, 111, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(200, 220, 171, 16))
        self.label_17.setObjectName("label_17")
        self.layoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_3.setGeometry(QtCore.QRect(40, 290, 301, 22))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.horizontalLayout_5.addWidget(self.lineEdit_14)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.horizontalLayout_5.addWidget(self.lineEdit_15)
        self.layoutWidget_4 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_4.setGeometry(QtCore.QRect(40, 370, 301, 22))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.horizontalLayout_6.addWidget(self.lineEdit_16)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.horizontalLayout_6.addWidget(self.lineEdit_17)
        self.layoutWidget_5 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_5.setGeometry(QtCore.QRect(40, 440, 301, 22))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.horizontalLayout_7.addWidget(self.lineEdit_18)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.horizontalLayout_7.addWidget(self.lineEdit_19)
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(30, 270, 171, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(210, 270, 171, 16))
        self.label_19.setObjectName("label_19")
        self.layoutWidget_10 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_10.setGeometry(QtCore.QRect(200, 330, 160, 34))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_10)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_21 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_2.addWidget(self.label_21)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_2.addWidget(self.label_25)
        self.layoutWidget_11 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_11.setGeometry(QtCore.QRect(30, 400, 160, 34))
        self.layoutWidget_11.setObjectName("layoutWidget_11")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_11)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_22 = QtWidgets.QLabel(self.layoutWidget_11)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_3.addWidget(self.label_22)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget_11)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_3.addWidget(self.label_26)
        self.layoutWidget_12 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_12.setGeometry(QtCore.QRect(200, 400, 160, 34))
        self.layoutWidget_12.setObjectName("layoutWidget_12")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_12)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_23 = QtWidgets.QLabel(self.layoutWidget_12)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_4.addWidget(self.label_23)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget_12)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_4.addWidget(self.label_27)
        self.layoutWidget_6 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_6.setGeometry(QtCore.QRect(410, 290, 301, 22))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.horizontalLayout_8.addWidget(self.lineEdit_20)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem11)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.horizontalLayout_8.addWidget(self.lineEdit_21)
        self.layoutWidget_7 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_7.setGeometry(QtCore.QRect(410, 240, 301, 22))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.horizontalLayout_9.addWidget(self.lineEdit_22)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem12)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.horizontalLayout_9.addWidget(self.lineEdit_23)
        self.label_28 = QtWidgets.QLabel(Dialog)
        self.label_28.setGeometry(QtCore.QRect(580, 270, 171, 16))
        self.label_28.setObjectName("label_28")
        self.layoutWidget_13 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_13.setGeometry(QtCore.QRect(400, 400, 160, 34))
        self.layoutWidget_13.setObjectName("layoutWidget_13")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_13)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_29 = QtWidgets.QLabel(self.layoutWidget_13)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_5.addWidget(self.label_29)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget_13)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_5.addWidget(self.label_30)
        self.layoutWidget_14 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_14.setGeometry(QtCore.QRect(570, 400, 160, 34))
        self.layoutWidget_14.setObjectName("layoutWidget_14")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_14)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_31 = QtWidgets.QLabel(self.layoutWidget_14)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_6.addWidget(self.label_31)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget_14)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_6.addWidget(self.label_32)
        self.layoutWidget_8 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_8.setGeometry(QtCore.QRect(400, 330, 160, 34))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget_8)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_33 = QtWidgets.QLabel(self.layoutWidget_8)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_7.addWidget(self.label_33)
        self.label_34 = QtWidgets.QLabel(self.layoutWidget_8)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_7.addWidget(self.label_34)
        self.label_35 = QtWidgets.QLabel(Dialog)
        self.label_35.setGeometry(QtCore.QRect(400, 270, 171, 16))
        self.label_35.setObjectName("label_35")
        self.layoutWidget_15 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_15.setGeometry(QtCore.QRect(570, 330, 160, 34))
        self.layoutWidget_15.setObjectName("layoutWidget_15")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget_15)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_36 = QtWidgets.QLabel(self.layoutWidget_15)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_8.addWidget(self.label_36)
        self.label_37 = QtWidgets.QLabel(self.layoutWidget_15)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_8.addWidget(self.label_37)
        self.label_38 = QtWidgets.QLabel(Dialog)
        self.label_38.setGeometry(QtCore.QRect(570, 220, 171, 16))
        self.label_38.setObjectName("label_38")
        self.layoutWidget_9 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_9.setGeometry(QtCore.QRect(410, 370, 301, 22))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget_9)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.layoutWidget_9)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.horizontalLayout_10.addWidget(self.lineEdit_24)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem13)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.layoutWidget_9)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.horizontalLayout_10.addWidget(self.lineEdit_25)
        self.layoutWidget_16 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_16.setGeometry(QtCore.QRect(410, 440, 301, 22))
        self.layoutWidget_16.setObjectName("layoutWidget_16")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget_16)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.layoutWidget_16)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.horizontalLayout_11.addWidget(self.lineEdit_26)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem14)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.layoutWidget_16)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.horizontalLayout_11.addWidget(self.lineEdit_27)
        self.label_39 = QtWidgets.QLabel(Dialog)
        self.label_39.setGeometry(QtCore.QRect(290, 480, 181, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.layoutWidget2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(40, 240, 301, 22))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_4.addWidget(self.lineEdit_12)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem15)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.horizontalLayout_4.addWidget(self.lineEdit_13)
        self.layoutWidget3 = QtWidgets.QWidget(Dialog)
        self.layoutWidget3.setGeometry(QtCore.QRect(30, 330, 160, 34))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_20.setObjectName("label_20")
        self.verticalLayout.addWidget(self.label_20)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_24.setObjectName("label_24")
        self.verticalLayout.addWidget(self.label_24)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(340, 510, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_40 = QtWidgets.QLabel(Dialog)
        self.label_40.setGeometry(QtCore.QRect(430, 220, 111, 16))
        self.label_40.setObjectName("label_40")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_9.setText(_translate("Dialog", "General flight parameters (common to both Along and Cross flight)"))
        self.label.setText(_translate("Dialog", "Ground Sample Distance (GSD) [m]:"))
        self.label_2.setText(_translate("Dialog", "Total number of images:"))
        self.label_3.setText(_translate("Dialog", "Pixel Size [mm]:"))
        self.label_4.setText(_translate("Dialog", "Sigma in Z direction [m]:"))
        self.label_6.setText(_translate("Dialog", "Image Footprint Width [m]:"))
        self.label_7.setText(_translate("Dialog", "Image Footprint Length [m]:"))
        self.label_8.setText(_translate("Dialog", "UAS minimum speed [m/s]:"))
        self.label_10.setText(_translate("Dialog", "Maximum distance allowed [m]:"))
        self.label_11.setText(_translate("Dialog", "Base line Along Track [m]:"))
        self.label_12.setText(_translate("Dialog", "Base line Cross Track [m]:"))
        self.label_13.setText(_translate("Dialog", "Maximum distance in project [m]:"))
        self.label_14.setText(_translate("Dialog", "Along Track Flight:"))
        self.label_15.setText(_translate("Dialog", "Cross Track Flight:"))
        self.label_16.setText(_translate("Dialog", "Number of Stripes:"))
        self.label_17.setText(_translate("Dialog", "Number of Images in One Stripe:"))
        self.label_18.setText(_translate("Dialog", "Real Base line in Cross Track [m]:"))
        self.label_19.setText(_translate("Dialog", "Real Cross Track Overlapping [%]:"))
        self.label_21.setText(_translate("Dialog", "Sigma Cross Flight Direction [m]: "))
        self.label_25.setText(_translate("Dialog", "(for a couple of images)"))
        self.label_22.setText(_translate("Dialog", "Sigma Along Flight Direction [m]: "))
        self.label_26.setText(_translate("Dialog", "(for a couple of images)"))
        self.label_23.setText(_translate("Dialog", "Number of Overlapped Images"))
        self.label_27.setText(_translate("Dialog", "for each Point Cross Track: "))
        self.label_28.setText(_translate("Dialog", "Real Cross Track Overlapping [%]:"))
        self.label_29.setText(_translate("Dialog", "Sigma Along Flight Direction [m]: "))
        self.label_30.setText(_translate("Dialog", "(for a couple of images)"))
        self.label_31.setText(_translate("Dialog", "Number of Overlapped Images"))
        self.label_32.setText(_translate("Dialog", "for each Point Cross Track: "))
        self.label_33.setText(_translate("Dialog", "Sigma Along Flight Direction [m]: "))
        self.label_34.setText(_translate("Dialog", "(for a couple of images)"))
        self.label_35.setText(_translate("Dialog", "Real Base line in Cross Track [m]:"))
        self.label_36.setText(_translate("Dialog", "Sigma Cross Flight Direction [m]: "))
        self.label_37.setText(_translate("Dialog", "(for a couple of images)"))
        self.label_38.setText(_translate("Dialog", "Number of Images in One Stripe:"))
        self.label_39.setText(_translate("Dialog", "Map of Accuracy - 𝝈_𝒁 [mm]:"))
        self.label_20.setText(_translate("Dialog", "Sigma Along Flight Direction [m]: "))
        self.label_24.setText(_translate("Dialog", "(for a couple of images)"))
        self.pushButton.setText(_translate("Dialog", "Plot"))
        self.label_40.setText(_translate("Dialog", "Number of Stripes:"))

