# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DSP_outputs.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Outputs(object):
    def setupUi(self, Outputs):
        Outputs.setObjectName("Outputs")
        Outputs.resize(771, 485)
        self.label_9 = QtWidgets.QLabel(Outputs)
        self.label_9.setGeometry(QtCore.QRect(320, 10, 271, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label = QtWidgets.QLabel(Outputs)
        self.label.setGeometry(QtCore.QRect(60, 40, 121, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Outputs)
        self.label_2.setGeometry(QtCore.QRect(60, 240, 131, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Outputs)
        self.label_3.setGeometry(QtCore.QRect(80, 90, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(Outputs)
        self.label_6.setGeometry(QtCore.QRect(380, 40, 141, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Outputs)
        self.label_7.setGeometry(QtCore.QRect(550, 40, 141, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Outputs)
        self.label_8.setGeometry(QtCore.QRect(210, 90, 151, 16))
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(Outputs)
        self.label_10.setGeometry(QtCore.QRect(370, 90, 151, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Outputs)
        self.label_11.setGeometry(QtCore.QRect(80, 140, 151, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Outputs)
        self.label_12.setGeometry(QtCore.QRect(230, 140, 151, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Outputs)
        self.label_13.setGeometry(QtCore.QRect(540, 90, 171, 16))
        self.label_13.setObjectName("label_13")
        self.label_19 = QtWidgets.QLabel(Outputs)
        self.label_19.setGeometry(QtCore.QRect(370, 190, 171, 16))
        self.label_19.setObjectName("label_19")
        self.label_39 = QtWidgets.QLabel(Outputs)
        self.label_39.setGeometry(QtCore.QRect(410, 310, 191, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.pb_error = QtWidgets.QPushButton(Outputs)
        self.pb_error.setGeometry(QtCore.QRect(430, 340, 75, 23))
        self.pb_error.setObjectName("pb_error")
        self.label_40 = QtWidgets.QLabel(Outputs)
        self.label_40.setGeometry(QtCore.QRect(60, 190, 111, 16))
        self.label_40.setObjectName("label_40")
        self.label_5 = QtWidgets.QLabel(Outputs)
        self.label_5.setGeometry(QtCore.QRect(220, 40, 121, 16))
        self.label_5.setObjectName("label_5")
        self.label_14 = QtWidgets.QLabel(Outputs)
        self.label_14.setGeometry(QtCore.QRect(410, 140, 81, 16))
        self.label_14.setObjectName("label_14")
        self.label_41 = QtWidgets.QLabel(Outputs)
        self.label_41.setGeometry(QtCore.QRect(570, 140, 151, 16))
        self.label_41.setObjectName("label_41")
        self.label_44 = QtWidgets.QLabel(Outputs)
        self.label_44.setGeometry(QtCore.QRect(220, 190, 111, 16))
        self.label_44.setObjectName("label_44")
        self.label_20 = QtWidgets.QLabel(Outputs)
        self.label_20.setGeometry(QtCore.QRect(550, 190, 171, 16))
        self.label_20.setObjectName("label_20")
        self.label_42 = QtWidgets.QLabel(Outputs)
        self.label_42.setGeometry(QtCore.QRect(240, 310, 181, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.pb_overlap = QtWidgets.QPushButton(Outputs)
        self.pb_overlap.setGeometry(QtCore.QRect(250, 340, 75, 23))
        self.pb_overlap.setObjectName("pb_overlap")
        self.GSDw = QtWidgets.QLabel(Outputs)
        self.GSDw.setGeometry(QtCore.QRect(70, 60, 91, 21))
        self.GSDw.setAutoFillBackground(False)
        self.GSDw.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"")
        self.GSDw.setText("")
        self.GSDw.setObjectName("GSDw")
        self.GSDh = QtWidgets.QLabel(Outputs)
        self.GSDh.setGeometry(QtCore.QRect(230, 60, 91, 21))
        self.GSDh.setAutoFillBackground(False)
        self.GSDh.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"")
        self.GSDh.setText("")
        self.GSDh.setObjectName("GSDh")
        self.footprint_W = QtWidgets.QLabel(Outputs)
        self.footprint_W.setGeometry(QtCore.QRect(400, 60, 91, 21))
        self.footprint_W.setAutoFillBackground(False)
        self.footprint_W.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"")
        self.footprint_W.setText("")
        self.footprint_W.setObjectName("footprint_W")
        self.footprint_H = QtWidgets.QLabel(Outputs)
        self.footprint_H.setGeometry(QtCore.QRect(570, 60, 91, 21))
        self.footprint_H.setAutoFillBackground(False)
        self.footprint_H.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"")
        self.footprint_H.setText("")
        self.footprint_H.setObjectName("footprint_H")
        self.px_size = QtWidgets.QLabel(Outputs)
        self.px_size.setGeometry(QtCore.QRect(70, 110, 91, 21))
        self.px_size.setAutoFillBackground(False)
        self.px_size.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"")
        self.px_size.setText("")
        self.px_size.setObjectName("px_size")
        self.UAS_min_speed = QtWidgets.QLabel(Outputs)
        self.UAS_min_speed.setGeometry(QtCore.QRect(230, 110, 91, 21))
        self.UAS_min_speed.setAutoFillBackground(False)
        self.UAS_min_speed.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"")
        self.UAS_min_speed.setText("")
        self.UAS_min_speed.setObjectName("UAS_min_speed")
        self.max_dist = QtWidgets.QLabel(Outputs)
        self.max_dist.setGeometry(QtCore.QRect(400, 110, 91, 21))
        self.max_dist.setAutoFillBackground(False)
        self.max_dist.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"")
        self.max_dist.setText("")
        self.max_dist.setObjectName("max_dist")
        self.max_dist_proj = QtWidgets.QLabel(Outputs)
        self.max_dist_proj.setGeometry(QtCore.QRect(570, 110, 91, 21))
        self.max_dist_proj.setAutoFillBackground(False)
        self.max_dist_proj.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"")
        self.max_dist_proj.setText("")
        self.max_dist_proj.setObjectName("max_dist_proj")
        self.baseline = QtWidgets.QLabel(Outputs)
        self.baseline.setGeometry(QtCore.QRect(70, 160, 91, 21))
        self.baseline.setAutoFillBackground(False)
        self.baseline.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"")
        self.baseline.setText("")
        self.baseline.setObjectName("baseline")
        self.b_real = QtWidgets.QLabel(Outputs)
        self.b_real.setGeometry(QtCore.QRect(230, 160, 91, 21))
        self.b_real.setAutoFillBackground(False)
        self.b_real.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"")
        self.b_real.setText("")
        self.b_real.setObjectName("b_real")
        self.interaxie = QtWidgets.QLabel(Outputs)
        self.interaxie.setGeometry(QtCore.QRect(400, 160, 91, 21))
        self.interaxie.setAutoFillBackground(False)
        self.interaxie.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"")
        self.interaxie.setText("")
        self.interaxie.setObjectName("interaxie")
        self.i_real = QtWidgets.QLabel(Outputs)
        self.i_real.setGeometry(QtCore.QRect(570, 160, 91, 21))
        self.i_real.setAutoFillBackground(False)
        self.i_real.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"")
        self.i_real.setText("")
        self.i_real.setObjectName("i_real")
        self.nstrip_x = QtWidgets.QLabel(Outputs)
        self.nstrip_x.setGeometry(QtCore.QRect(70, 210, 91, 21))
        self.nstrip_x.setAutoFillBackground(False)
        self.nstrip_x.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"")
        self.nstrip_x.setText("")
        self.nstrip_x.setObjectName("nstrip_x")
        self.nstrip_y = QtWidgets.QLabel(Outputs)
        self.nstrip_y.setGeometry(QtCore.QRect(230, 210, 91, 21))
        self.nstrip_y.setAutoFillBackground(False)
        self.nstrip_y.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"")
        self.nstrip_y.setText("")
        self.nstrip_y.setObjectName("nstrip_y")
        self.n_img = QtWidgets.QLabel(Outputs)
        self.n_img.setGeometry(QtCore.QRect(70, 260, 91, 21))
        self.n_img.setAutoFillBackground(False)
        self.n_img.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"")
        self.n_img.setText("")
        self.n_img.setObjectName("n_img")
        self.Rl_real = QtWidgets.QLabel(Outputs)
        self.Rl_real.setGeometry(QtCore.QRect(400, 210, 91, 21))
        self.Rl_real.setAutoFillBackground(False)
        self.Rl_real.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"")
        self.Rl_real.setText("")
        self.Rl_real.setObjectName("Rl_real")
        self.Rt_real = QtWidgets.QLabel(Outputs)
        self.Rt_real.setGeometry(QtCore.QRect(570, 210, 91, 21))
        self.Rt_real.setAutoFillBackground(False)
        self.Rt_real.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"")
        self.Rt_real.setText("")
        self.Rt_real.setObjectName("Rt_real")
        self.tb_browse = QtWidgets.QToolButton(Outputs)
        self.tb_browse.setGeometry(QtCore.QRect(520, 410, 31, 21))
        self.tb_browse.setObjectName("tb_browse")
        self.lineEdit = QtWidgets.QLineEdit(Outputs)
        self.lineEdit.setGeometry(QtCore.QRect(250, 410, 261, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_15 = QtWidgets.QLabel(Outputs)
        self.label_15.setGeometry(QtCore.QRect(200, 410, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.h = QtWidgets.QLabel(Outputs)
        self.h.setGeometry(QtCore.QRect(230, 260, 91, 21))
        self.h.setAutoFillBackground(False)
        self.h.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"")
        self.h.setText("")
        self.h.setObjectName("h")
        self.Rl = QtWidgets.QLabel(Outputs)
        self.Rl.setGeometry(QtCore.QRect(400, 260, 91, 21))
        self.Rl.setAutoFillBackground(False)
        self.Rl.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"")
        self.Rl.setText("")
        self.Rl.setObjectName("Rl")
        self.Rt = QtWidgets.QLabel(Outputs)
        self.Rt.setGeometry(QtCore.QRect(570, 260, 91, 21))
        self.Rt.setAutoFillBackground(False)
        self.Rt.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;\n"
"")
        self.Rt.setText("")
        self.Rt.setObjectName("Rt")
        self.label_18 = QtWidgets.QLabel(Outputs)
        self.label_18.setGeometry(QtCore.QRect(230, 240, 83, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_16 = QtWidgets.QLabel(Outputs)
        self.label_16.setGeometry(QtCore.QRect(370, 240, 143, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Outputs)
        self.label_17.setGeometry(QtCore.QRect(550, 240, 143, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")

        self.retranslateUi(Outputs)
        QtCore.QMetaObject.connectSlotsByName(Outputs)

    def retranslateUi(self, Outputs):
        _translate = QtCore.QCoreApplication.translate
        Outputs.setWindowTitle(_translate("Outputs", "Outputs"))
        self.label_9.setText(_translate("Outputs", "Flight parameters:"))
        self.label.setText(_translate("Outputs", "GSD - Width (GSDw)[m]:"))
        self.label_2.setText(_translate("Outputs", "Total number of images:"))
        self.label_3.setText(_translate("Outputs", "Pixel Size [mm]:"))
        self.label_6.setText(_translate("Outputs", "Image Footprint Width [m]:"))
        self.label_7.setText(_translate("Outputs", "Image Footprint Height [m]:"))
        self.label_8.setText(_translate("Outputs", "UAS minimum speed [m/s]:"))
        self.label_10.setText(_translate("Outputs", "Maximum distance allowed [km]:"))
        self.label_11.setText(_translate("Outputs", "Baseline [m]:"))
        self.label_12.setText(_translate("Outputs", "Real Baseline [m]:"))
        self.label_13.setText(_translate("Outputs", "Maximum distance in project [km]:"))
        self.label_19.setText(_translate("Outputs", "Real Longitudinal Overlapping [%]:"))
        self.label_39.setText(_translate("Outputs", "Estimated Error Map:"))
        self.pb_error.setText(_translate("Outputs", "Plot"))
        self.label_40.setText(_translate("Outputs", "Number of Stripes in X:"))
        self.label_5.setText(_translate("Outputs", "GSD- Height (GSDh) [m]:"))
        self.label_14.setText(_translate("Outputs", "Interaxie [m]:"))
        self.label_41.setText(_translate("Outputs", "Real Interaxie [m]:"))
        self.label_44.setText(_translate("Outputs", "Number of Stripes in Y:"))
        self.label_20.setText(_translate("Outputs", "Real transversal Overlapping [%]:"))
        self.label_42.setText(_translate("Outputs", "Overlapping Map:"))
        self.pb_overlap.setText(_translate("Outputs", "Plot"))
        self.tb_browse.setText(_translate("Outputs", "..."))
        self.label_15.setText(_translate("Outputs", "Export:"))
        self.label_18.setText(_translate("Outputs", "Flight Height [m]:"))
        self.label_16.setText(_translate("Outputs", "Along Track Overlapping [%]:"))
        self.label_17.setText(_translate("Outputs", "Cross Track Overlapping [%]:"))

